config/routes.rb
Rails.application.routes.draw do
  # route used by new relic to monitor uptime fo app
  get '/ping', to: 'application#ping'

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  # This line mounts Spree's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Spree relies on it being the default of "spree"
  mount Spree::Core::Engine, at: '/'

  root :to => "company_store#index"

  post '/charges', to: 'spree/api/charges#charge'
  get 'accept/:order_id', to: 'spree/purchases#purchase_payment'
  get 'csaccept/:order_id', to: 'spree/purchases#csaccept'
  post '/customer', to: 'spree/api/charges#create_customer'
  post '/delete_customer/:customer_id', to: 'spree/api/charges#delete_customer'
  post '/confirm', to: 'spree/api/charges#confirm_deposit'
  post '/send_request', to: 'spree/home#send_request'

  get '/company_store', to: 'spree/company_store#index'
  get '/company_store/:id', to: 'spree/company_store#show'
  post '/inspire_me_request', to: 'spree/company_store#inspire_me'
  get 'company_store/:id/products', to: 'spree/company_store#products'
  get 'company_store/:id/login', to: 'spree/company_store_sessions#new'
  post 'company_store/:id/login', to: 'spree/company_store_sessions#create', as: :create_new_company_store_session

  resources :auctions,
    controller: 'spree/auctions',
    as: 'auctions' do
      collection do
        post 'upload_proof'
      end
      member do
        get 'download_proof'
      end
    end

  resources :dashboards, controller: 'spree/dashboards', as: 'dashboards', only: [:index]
  resources :invoices, controller: 'spree/invoices', as: 'invoices', only: [:index, :show]

  resources :logos,
    controller: 'spree/logos',
    as: 'logos' do
      member do
        get 'download_logo'
      end
    end

  resources :purchases,
    controller: 'spree/purchases',
    as: 'purchases',
    only: [:new, :create]

  resources :product_requests,
    controller: 'spree/product_requests',
    as: 'product_requests',
    only: [:create]

  scope :api do
    resources :auctions, controller: 'spree/api/auctions' do
      member do
        post 'tracking'
        post 'confirmed_delivery'
        get 'tracking_information'
        post 'approve_proof'
        post 'reject_proof'
      end
      resources :bids, controller: 'spree/api/bids' do
        post 'accept'
      end
    end
    resources :bids, controller: 'spree/api/bids', as: 'api_bids'
    match '/bids/:id/accept' => 'spree/api/bids#accept', via: :post
    resources :taxrates, controller: 'spree/api/taxrates', as: 'api_taxrates'
    post '/auctions/:id/order_confirm' => 'spree/api/auctions#order_confirm'
    post '/auctions/:id/in_production' => 'spree/api/auctions#in_production'
    post '/auctions/:id/claim_payment' => 'spree/api/auctions#claim_payment'
    post '/auctions/:id/reject_order' => 'spree/api/auctions#reject_order'
    post '/auctions/:id/resolve_dispute' => 'spree/api/auctions#resolve_dispute'
    post '/products/:id/best_price' => 'spree/api/products#best_price'
    post '/products/:id/configure' => 'spree/api/products#configure'

    resources :request_ideas, controller: 'spree/api/request_ideas' do
      member do
        post 'sample_request'
      end
    end

    resources :product_requests, controller: 'spree/api/product_requests'

    resources :charges, controller: 'spree/api/charges', only: [:index]
  end

  post 'product_requests/:request_idea_id/destroy' => 'spree/admin/product_requests#destroy_idea'
  post 'product_requests/:request_idea_id/update' => 'spree/admin/product_requests#update_idea'

  Spree::Core::Engine.routes.draw do
    namespace :admin do
      resources :product_requests do
        member do
          post 'generate_notification'
        end
      end
      resources :company_stores do
        member do
          post :clone
        end
        resources :markups
      end
      resources :product_loads
      resources :pms_colors
      resources :imprint_methods
      resources :option_mappings
      resources :product_reports
      resources :upcharge_types
      resources :pms_colors_suppliers
      resources :suppliers do
        get :addresses
        put :addresses
        get :imprint_methods
        put :imprint_methods
      end

      delete '/markups/:id', to: 'markups#destroy', as: :markup
    end
  end

  Spree::Core::Engine.add_routes do
    namespace :admin do
      resources :products do
        resources :color_products
        resources :imprint_methods_products
        resources :upcharge_products
        resources :cartons
        resources :preconfigure
        resources :gooten_prices
      end

      resources :taxonomies do
        resources :taxons do
          resources :images, controller: :taxon_images do
            collection do
              post :update_positions
            end
          end
        end
      end

      resources :users do
        resources :logos

        member do
          get :addresses
          put :addresses
          put :clear_api_key
          put :generate_api_key
          get :items
          get :orders
        end
      end
    end
  end
end

app/models/spree/color_product.rb
class Spree::ColorProduct < Spree::Base
  belongs_to :product
  has_many :purchases

  validates :product, presence: true
  validates :color, presence: true
end

app/controllers/spree/admin/color_products_controller.rb
class Spree::Admin::ColorProductsController < Spree::Admin::ResourceController
  before_action :load_product
  before_action :load_color_product, only: [:edit, :update, :destroy]
  before_action :load_color_products, only: [:index]
  after_action :set_validity, only: [:create, :update, :destroy]

  private

  def set_validity
    @product.loading!
    @product.check_validity!
    @product.loaded! if @product.state == 'loading'
  end

  def load_product
    @product = Spree::Product.friendly.find(params[:product_id])
  end

  def load_color_product
    @color_product = Spree::ColorProduct.find(params[:id])
  end

  def load_color_products
    @color_products = Spree::ColorProduct.where(product: @product)
  end

  def location_after_save
    admin_product_color_products_url(@product)
  end

  def color_product_params
    params.require(:color_product).permit(:color, :product_id)
  end
end

app/views/spree/admin/color_products/_form.html.erb
<div class="row">
  <div class="col-md-12">
    <%= f.hidden_field :product_id, value: @product.id %>

    <%= f.field_container :name, class: ['form-group'] do %>
      <%= f.label :color, Spree.t(:color) %>
      <span class='required'>*</span>
      <%= f.text_field :color, class: 'form-control' %>
      <%= f.error_message_on :color %>
    <% end %>
  </div>
</div>

app/views/spree/admin/color_products/edit.html.erb
<%= render partial: 'spree/admin/shared/product_tabs', locals: { current: :color_products } %>
<%= render partial: 'spree/admin/shared/error_messages', locals: { target: @color_product } %>

<%= form_for [:admin, @color_product], url: admin_product_color_product_path(@product, @color_product) do |f| %>
  <fieldset>
    <%= render partial: 'form', locals: { f: f } %>

    <div class="form-actions">
      <%= button Spree.t('actions.update'), 'save' %>
      <span class="or"><%= Spree.t(:or) %></span>
      <%= button_link_to Spree.t('actions.cancel'), spree.admin_product_color_products_url(@product), icon: 'delete', id: 'cancel_link' %>
    </div>
  </fieldset>
<% end %>

app/views/spree/admin/color_products/index.html.erb
<%= render partial: 'spree/admin/shared/product_tabs', locals: { current: :color_products } %>

<% content_for :page_actions do %>
  <% if can?(:create, Spree::ColorProduct) %>
    <%= button_link_to Spree.t(:new_color), new_admin_product_color_product_path, { class: 'btn-success', icon: 'add' } %>
  <% end %>
<% end %>

<div class="well">
  <% if @color_products.any? %>
    <table class='table sortable' data-hook='colors_table'>
      <thead>
        <tr data-hook="images_header">
          <th>
            <%= Spree.t(:color) %>
          </th>
          <th class="actions actions-2"></th>
        </tr>
      </thead>
      <tbody>
        <% @color_products.each do |color_product| %>
          <tr id='<%= spree_dom_id color_product %>'>
            <td>
              <p><%= color_product.color %></p>
            </td>
            <td class="actions actions-2 text-right">
              <%= link_to_with_icon('edit', Spree.t(:edit), edit_admin_product_color_product_path(color_product.product, color_product), class: 'btn btn-primary btn-sm', no_text: true, data: { action: :edit }) if can? :edit, color_product %>
              <%= link_to_delete(color_product, { url: admin_product_color_product_path(color_product.product, color_product), no_text: true }) if can? :destroy, color_product %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <div class="alert alert-info no-objects-found">
      <%= Spree.t(:no_resource_found, resource: plural_resource_name(Spree::ColorProduct)) %>.
    </div>
  <% end %>
</div>

app/views/spree/admin/color_products/new.html.erb
<%= render partial: 'spree/admin/shared/product_tabs', locals: { current: :color_products } %>
<%= render partial: 'spree/admin/shared/error_messages', locals: { target: @color_product } %>

<%= form_for [:admin, @color_product], url: "/admin/products/#{@product.id}/color_products", html: { method: :post } do |f| %>
  <fieldset>
    <%= render partial: 'form', locals: { f: f } %>

    <div class="form-actions">
      <%= button Spree.t('actions.save'), 'save' %>
      <span class="or"><%= Spree.t(:or) %></span>
      <%= button_link_to Spree.t('actions.cancel'), spree.admin_product_color_products_url(@product), icon: 'delete', id: 'cancel_link' %>
    </div>
  </fieldset>
<% end %>