config/routes.rb
Rails.application.routes.draw do
  # route used by new relic to monitor uptime fo app
  get '/ping', to: 'application#ping'

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  # This line mounts Spree's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Spree relies on it being the default of "spree"
  mount Spree::Core::Engine, at: '/'

  root :to => "company_store#index"

  post '/charges', to: 'spree/api/charges#charge'
  get 'accept/:order_id', to: 'spree/purchases#purchase_payment'
  get 'csaccept/:order_id', to: 'spree/purchases#csaccept'
  post '/customer', to: 'spree/api/charges#create_customer'
  post '/delete_customer/:customer_id', to: 'spree/api/charges#delete_customer'
  post '/confirm', to: 'spree/api/charges#confirm_deposit'
  post '/send_request', to: 'spree/home#send_request'

  get '/company_store', to: 'spree/company_store#index'
  get '/company_store/:id', to: 'spree/company_store#show'
  post '/inspire_me_request', to: 'spree/company_store#inspire_me'
  get 'company_store/:id/products', to: 'spree/company_store#products'
  get 'company_store/:id/login', to: 'spree/company_store_sessions#new'
  post 'company_store/:id/login', to: 'spree/company_store_sessions#create', as: :create_new_company_store_session

  resources :auctions,
    controller: 'spree/auctions',
    as: 'auctions' do
      collection do
        post 'upload_proof'
      end
      member do
        get 'download_proof'
      end
    end

  resources :dashboards, controller: 'spree/dashboards', as: 'dashboards', only: [:index]
  resources :invoices, controller: 'spree/invoices', as: 'invoices', only: [:index, :show]

  resources :logos,
    controller: 'spree/logos',
    as: 'logos' do
      member do
        get 'download_logo'
      end
    end

  resources :purchases,
    controller: 'spree/purchases',
    as: 'purchases',
    only: [:new, :create]

  resources :product_requests,
    controller: 'spree/product_requests',
    as: 'product_requests',
    only: [:create]

  scope :api do
    resources :auctions, controller: 'spree/api/auctions' do
      member do
        post 'tracking'
        post 'confirmed_delivery'
        get 'tracking_information'
        post 'approve_proof'
        post 'reject_proof'
      end
      resources :bids, controller: 'spree/api/bids' do
        post 'accept'
      end
    end
    resources :bids, controller: 'spree/api/bids', as: 'api_bids'
    match '/bids/:id/accept' => 'spree/api/bids#accept', via: :post
    resources :taxrates, controller: 'spree/api/taxrates', as: 'api_taxrates'
    post '/auctions/:id/order_confirm' => 'spree/api/auctions#order_confirm'
    post '/auctions/:id/in_production' => 'spree/api/auctions#in_production'
    post '/auctions/:id/claim_payment' => 'spree/api/auctions#claim_payment'
    post '/auctions/:id/reject_order' => 'spree/api/auctions#reject_order'
    post '/auctions/:id/resolve_dispute' => 'spree/api/auctions#resolve_dispute'
    post '/products/:id/best_price' => 'spree/api/products#best_price'
    post '/products/:id/configure' => 'spree/api/products#configure'

    resources :request_ideas, controller: 'spree/api/request_ideas' do
      member do
        post 'sample_request'
      end
    end

    resources :product_requests, controller: 'spree/api/product_requests'

    resources :charges, controller: 'spree/api/charges', only: [:index]
  end

  post 'product_requests/:request_idea_id/destroy' => 'spree/admin/product_requests#destroy_idea'
  post 'product_requests/:request_idea_id/update' => 'spree/admin/product_requests#update_idea'

  Spree::Core::Engine.routes.draw do
    namespace :admin do
      resources :product_requests do
        member do
          post 'generate_notification'
        end
      end
      resources :company_stores do
        member do
          post :clone
        end
        resources :markups
      end
      resources :product_loads
      resources :pms_colors
      resources :imprint_methods
      resources :option_mappings
      resources :product_reports
      resources :upcharge_types
      resources :pms_colors_suppliers
      resources :suppliers do
        get :addresses
        put :addresses
        get :imprint_methods
        put :imprint_methods
      end

      delete '/markups/:id', to: 'markups#destroy', as: :markup
    end
  end

  Spree::Core::Engine.add_routes do
    namespace :admin do
      resources :products do
        resources :color_products
        resources :imprint_methods_products
        resources :upcharge_products
        resources :cartons
        resources :preconfigure
        resources :gooten_prices
      end

      resources :taxonomies do
        resources :taxons do
          resources :images, controller: :taxon_images do
            collection do
              post :update_positions
            end
          end
        end
      end

      resources :users do
        resources :logos

        member do
          get :addresses
          put :addresses
          put :clear_api_key
          put :generate_api_key
          get :items
          get :orders
        end
      end
    end
  end
end

app/models/spree/pms_colors_supplier.rb
class Spree::PmsColorsSupplier < Spree::Base
  belongs_to :supplier
  belongs_to :pms_color
  belongs_to :imprint_method

  validates :supplier_id, presence: true
  validates :pms_color_id, presence: true
  validates :imprint_method_id, presence: true

  def self.to_csv
    attributes = %w(factory imprint_method name display_name pantone hex)
    CSV.generate(headers: true) do |csv|
      csv << attributes
      all.find_each do |myrow|
        row = []
        factory = Spree::Supplier.find(myrow.supplier_id)
        imprint_method = Spree::ImprintMethod.find(myrow.imprint_method_id)
        pms_color = Spree::PmsColor.find(myrow.pms_color_id)
        row << factory.name
        row << imprint_method.name
        row << pms_color.name
        row << pms_color.display_name
        row << pms_color.pantone
        row << pms_color.hex
        csv << row
      end
    end
  end
end

app/controllers/spree/admin/pms_colors_suppliers_controller.rb
class Spree::Admin::PmsColorsSuppliersController < Spree::Admin::ResourceController
  before_action :load_pms_colors_supplier, only: [:edit, :update]

  def index
    respond_with(@collection)
  end

  def create
    Spree::PmsColorsSupplier.create(pms_colors_supplier_params)
    redirect_to admin_pms_colors_suppliers_path
  end

  def update
    @pms_colors_supplier.update_attributes(pms_colors_supplier_params)
    redirect_to admin_pms_colors_suppliers_path
  end

  private

  def load_pms_colors_supplier
    @pms_colors_supplier = Spree::PmsColorsSupplier.find(params[:id])
  end

  def collection
    return @collection if @collection.present?
    params[:q] = {} if params[:q].blank?

    @collection = super
    @search = @collection.ransack(params[:q])
    @collection = @search.result
      .page(params[:page])
      .per(Spree::Config[:properties_per_page])

    @collection
  end

  def pms_colors_supplier_params
    params.require(:pms_colors_supplier).permit(
      :pms_color_id,
      :supplier_id,
      :display_name,
      :imprint_method_id
    )
  end
end

app/views/spree/admin/pms_colors_suppliers/_form.html.slim
.row
  .col-md-3
    = f.field_container :name, class: ['form-group'] do
      = f.label :supplier_id, "Supplier ID"
      span.required *
      = f.text_field :supplier_id, :class => 'form-control'
      = f.error_message_on :supplier_id
  .col-md-3
    = f.field_container :imprint_method_id, class: ['form-group'] do
      = f.label :imprint_method_id, "Imprint Method ID"
      = f.text_field :imprint_method_id, :class => 'form-control'
      = f.error_message_on :imprint_method_id
  .col-md-3
    = f.field_container :pms_color_id, class: ['form-group'] do
      = f.label :pms_color_id, "PMS Color ID"
      = f.text_field :pms_color_id, :class => 'form-control'
      = f.error_message_on :pms_color_id
  .col-md-3
    = f.field_container :display_name, class: ['form-group'] do
      = f.label :display_name, "Display Name"
      = f.text_field :display_name, :class => 'form-control'
      = f.error_message_on :display_name

app/views/spree/admin/pms_colors_suppliers/edit.html.slim
- content_for :page_title do
  = Spree.t(:editing_resource, resource: Spree::PmsColorsSupplier.model_name.human)

= render :partial => 'spree/admin/shared/error_messages', :locals => { :target => @pms_color }

= form_for [:admin, @pms_colors_supplier] do |f|
  fieldset
    = render :partial => 'form', :locals => { :f => f }
    = render :partial => 'spree/admin/shared/edit_resource_links'

app/views/spree/admin/pms_colors_suppliers/index.html.slim
- content_for :page_title do
 = plural_resource_name(Spree::PmsColorsSupplier)

 - content_for :page_actions do
  = button_link_to Spree.t(:new_pms_colors_supplier), new_admin_pms_colors_supplier_path, { :class => "btn-success", :icon => 'add', 'data-update' => 'new_pms_supplier_color', :id => 'new_pms_color_supplier_link' }

- content_for :table_filter do
  div
    = search_form_for [:admin, @search] do |f|
      - locals = {:f => f}
      .row
        .col-md-3
          .form-group
            = f.label :supplier_id_eq, "Supplier"
            = f.text_field :supplier_id_eq, :class => "form-control"
        .col-md-3
          .form-group
            = f.label :pms_color_id_eq, "PMS Color ID"
            = f.text_field :pms_color_id_eq, :class => "form-control"
        .col-md-3
          .form-group
            = f.label :imprint_method_id_eq, "Imprint ID"
            = f.text_field :imprint_method_id_eq, :class => "form-control"
        .col.col-md-3
          .form-group
            = f.label :display_name_cont, "Display Name"
            = f.text_field :display_name_cont, :class => "form-control js-quick-search-target"
      .form-actions
        = button Spree.t(:search), 'search'

.well
  - if @pms_colors_suppliers.any?
    table.table
      thead
        tr
          th Supplier ID
          th Imprint method ID
          th PMS Color ID
          th Display Name
          th Action
      tbody
        - @pms_colors_suppliers.each do |pms_color_supplier|
          tr
            td = "#{pms_color_supplier.supplier.name}(#{pms_color_supplier.supplier_id})"
            td = "#{pms_color_supplier.imprint_method.name}(#{pms_color_supplier.imprint_method_id})"
            td = "#{pms_color_supplier.pms_color.name}(#{pms_color_supplier.pms_color_id})"
            td = pms_color_supplier.display_name
            td.actions.actions-2.text-right
              = link_to_edit(pms_color_supplier, :no_text => true)
              = link_to_delete(pms_color_supplier, :no_text => true)
  - else
    .alert.alert-info.no-objects-found
    = Spree.t(:no_resource_found, resource: plural_resource_name(Spree::PmsColorsSupplier))
    = ","
    = link_to Spree.t(:add_one), new_object_url
    = "!"
= paginate @collection

app/views/spree/admin/pms_colors_suppliers/new.html.slim
- content_for :page_title do
  = Spree.t(:editing_resource, resource: Spree::PmsColorsSupplier.model_name.human)

= render :partial => 'spree/admin/shared/error_messages', :locals => { :target => @pms_color }

= form_for [:admin, @pms_colors_supplier] do |f|
  fieldset
    = render partial: 'form', locals: { f: f }
    = render :partial => 'spree/admin/shared/edit_resource_links'