config/routes.rb
Rails.application.routes.draw do
  # route used by new relic to monitor uptime fo app
  get '/ping', to: 'application#ping'

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  # This line mounts Spree's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Spree relies on it being the default of "spree"
  mount Spree::Core::Engine, at: '/'

  root :to => "company_store#index"

  post '/charges', to: 'spree/api/charges#charge'
  get 'accept/:order_id', to: 'spree/purchases#purchase_payment'
  get 'csaccept/:order_id', to: 'spree/purchases#csaccept'
  post '/customer', to: 'spree/api/charges#create_customer'
  post '/delete_customer/:customer_id', to: 'spree/api/charges#delete_customer'
  post '/confirm', to: 'spree/api/charges#confirm_deposit'
  post '/send_request', to: 'spree/home#send_request'

  get '/company_store', to: 'spree/company_store#index'
  get '/company_store/:id', to: 'spree/company_store#show'
  post '/inspire_me_request', to: 'spree/company_store#inspire_me'
  get 'company_store/:id/products', to: 'spree/company_store#products'
  get 'company_store/:id/login', to: 'spree/company_store_sessions#new'
  post 'company_store/:id/login', to: 'spree/company_store_sessions#create', as: :create_new_company_store_session

  resources :auctions,
    controller: 'spree/auctions',
    as: 'auctions' do
      collection do
        post 'upload_proof'
      end
      member do
        get 'download_proof'
      end
    end

  resources :dashboards, controller: 'spree/dashboards', as: 'dashboards', only: [:index]
  resources :invoices, controller: 'spree/invoices', as: 'invoices', only: [:index, :show]

  resources :logos,
    controller: 'spree/logos',
    as: 'logos' do
      member do
        get 'download_logo'
      end
    end

  resources :purchases,
    controller: 'spree/purchases',
    as: 'purchases',
    only: [:new, :create]

  resources :product_requests,
    controller: 'spree/product_requests',
    as: 'product_requests',
    only: [:create]

  scope :api do
    resources :auctions, controller: 'spree/api/auctions' do
      member do
        post 'tracking'
        post 'confirmed_delivery'
        get 'tracking_information'
        post 'approve_proof'
        post 'reject_proof'
      end
      resources :bids, controller: 'spree/api/bids' do
        post 'accept'
      end
    end
    resources :bids, controller: 'spree/api/bids', as: 'api_bids'
    match '/bids/:id/accept' => 'spree/api/bids#accept', via: :post
    resources :taxrates, controller: 'spree/api/taxrates', as: 'api_taxrates'
    post '/auctions/:id/order_confirm' => 'spree/api/auctions#order_confirm'
    post '/auctions/:id/in_production' => 'spree/api/auctions#in_production'
    post '/auctions/:id/claim_payment' => 'spree/api/auctions#claim_payment'
    post '/auctions/:id/reject_order' => 'spree/api/auctions#reject_order'
    post '/auctions/:id/resolve_dispute' => 'spree/api/auctions#resolve_dispute'
    post '/products/:id/best_price' => 'spree/api/products#best_price'
    post '/products/:id/configure' => 'spree/api/products#configure'

    resources :request_ideas, controller: 'spree/api/request_ideas' do
      member do
        post 'sample_request'
      end
    end

    resources :product_requests, controller: 'spree/api/product_requests'

    resources :charges, controller: 'spree/api/charges', only: [:index]
  end

  post 'product_requests/:request_idea_id/destroy' => 'spree/admin/product_requests#destroy_idea'
  post 'product_requests/:request_idea_id/update' => 'spree/admin/product_requests#update_idea'

  Spree::Core::Engine.routes.draw do
    namespace :admin do
      resources :product_requests do
        member do
          post 'generate_notification'
        end
      end
      resources :company_stores do
        member do
          post :clone
        end
        resources :markups
      end
      resources :product_loads
      resources :pms_colors
      resources :imprint_methods
      resources :option_mappings
      resources :product_reports
      resources :upcharge_types
      resources :pms_colors_suppliers
      resources :suppliers do
        get :addresses
        put :addresses
        get :imprint_methods
        put :imprint_methods
      end

      delete '/markups/:id', to: 'markups#destroy', as: :markup
    end
  end

  Spree::Core::Engine.add_routes do
    namespace :admin do
      resources :products do
        resources :color_products
        resources :imprint_methods_products
        resources :upcharge_products
        resources :cartons
        resources :preconfigure
        resources :gooten_prices
      end

      resources :taxonomies do
        resources :taxons do
          resources :images, controller: :taxon_images do
            collection do
              post :update_positions
            end
          end
        end
      end

      resources :users do
        resources :logos

        member do
          get :addresses
          put :addresses
          put :clear_api_key
          put :generate_api_key
          get :items
          get :orders
        end
      end
    end
  end
end

app/models/spree/imprint_method.rb
class Spree::ImprintMethod < Spree::Base
  has_and_belongs_to_many :products
  has_many :auctions
  has_many :purchases

  validates :name, presence: true
end

app/controllers/spree/admin/imprint_methods_controller.rb
class Spree::Admin::ImprintMethodsController < Spree::Admin::ResourceController
  before_action :load_imprint_method, only: [:edit, :update]

  respond_to :html

  def index
    respond_with(@collection)
  end

  def create
    Spree::ImprintMethod.create(imprint_method_params)
    redirect_to admin_imprint_methods_path
  end

  private

  def load_imprint_method
    @imprint_method = Spree::ImprintMethod.find(params[:id])
  end

  def collection
    return @collection if @collection.present?
    params[:q] = {} if params[:q].blank?

    @collection = super
    @search = @collection.ransack(params[:q])
    @collection = @search.result
      .page(params[:page])
      .per(Spree::Config[:properties_per_page])

    @collection
  end

  def imprint_method_params
    params.require(:imprint_method).permit(:name)
  end
end

app/views/spree/admin/imprint_methods/_form.html.erb
<div class="row">
  <div class="col-md-12">
    <%= f.field_container :name, class: ['form-group'] do %>
      <%= f.label :name, Spree.t(:name) %>
      <span class='required'>*</span>
      <%= f.text_field :name, class: 'form-control' %>
      <%= f.error_message_on :name %>
    <% end %>
  </div>
</div>

app/views/spree/admin/imprint_methods/edit.html.erb
<%= render partial: 'spree/admin/shared/product_tabs', locals: { current: :imprint_methods } %>
<%= render partial: 'spree/admin/shared/error_messages', locals: { target: @imprint_method } %>

<%= form_for [:admin, @imprint_method] do |f| %>
  <fieldset>
    <%= render partial: 'form', locals: { f: f } %>
    <%= render partial: 'spree/admin/shared/edit_resource_links' %>
  </fieldset>
<% end %>

app/views/spree/admin/imprint_methods/index.html.erb
<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:imprint_method), new_admin_imprint_method_path, { class: 'btn-success', icon: 'add' } %>
<% end %>

<% content_for :table_filter do %>
  <div data-hook="admin_imprint_methods_sidebar">
    <%= search_form_for [:admin, @search] do |f| %>
      <%- locals = { f: f } %>
      <div data-hook="admin_imprint_methods_index_search" class="row">
        <div class="col-md-6">
          <div class="form-group">
            <%= f.label :id_eq, Spree.t(:id) %>
            <%= f.text_field :id_eq, class: 'form-control js-quick-search-target' %>
          </div>
        </div>

        <div class="col-md-6">
          <div class="form-group">
            <%= f.label :name_cont, Spree.t(:name) %>
            <%= f.text_field :name_cont, class: 'form-control' %>
          </div>
        </div>
      </div>

      <div data-hook="admin_imprint_methods_index_search_buttons" class="form-actions">
        <%= button Spree.t(:search), 'search' %>
      </div>
    <% end %>
  </div>
<% end %>

<div class="well">
  <% if @imprint_methods.any? %>
    <table class='table sortable' data-hook='colors_table'>
      <thead>
        <tr>
          <th><%= Spree.t(:id) %></th>
          <th><%= Spree.t(:name) %></th>
          <th class="actions actions-2"></th>
        </tr>
      </thead>
      <tbody>
        <% @imprint_methods.each do |imprint_method| %>
          <tr id='<%= spree_dom_id imprint_method %>'>
            <td><p><%= imprint_method.id %></p></td>
            <td><p><%= imprint_method.name %></p></td>
            <td class="actions actions-2 text-right">
              <%= link_to_edit(imprint_method, no_text: true) %>
              <%= link_to_delete(imprint_method, no_text: true) %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <div class="alert alert-info no-objects-found">
      <%= Spree.t(:no_resource_found, resource: plural_resource_name(Spree::ImprintMethod)) %>.
    </div>
  <% end %>
</div>

<%= render partial: 'spree/admin/shared/index_table_options', locals: { collection: @collection } %>

app/views/spree/admin/imprint_methods/new.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:editing_resource, resource: Spree::ImprintMethod.model_name.human) %>
<% end %>

<%= render partial: 'spree/admin/shared/error_messages', locals: { target: @imprint_method } %>

<%= form_for [:admin, @imprint_method] do |f| %>
  <fieldset>
    <%= render partial: 'form', locals: { f: f } %>
    <%= render partial: 'spree/admin/shared/new_resource_links' %>
  </fieldset>
<% end %>